apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-project
  labels:
    app: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: django
        image: bimalkumar04/django-project:latest
        ports:
        - containerPort: 8000